name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
  push:
    branches: [main]
    paths:
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
  workflow_dispatch:
    inputs: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        py_version: ["3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: ${{ matrix.py_version }}
      BQ_PROJECT: ${{ secrets.BQ_PROJECT }}
      BQ_DATASET: ${{ secrets.BQ_DATASET }}
      BQ_CREDS: ${{ secrets.BQ_CREDS }}
      GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Setup Python ${{ matrix.py_version }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          python-version: ${{ matrix.py_version }}
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39
      - name: Install Target Bigquery
        run: uv sync --frozen
      - name: Run SDK Tests
        run: uv run --frozen pytest -k test_core
      - name: Run Bigquery Unit Tests
        run: uv run --frozen pytest -k test_utils
      - name: Run Bigquery Integration Tests
        run: uv run --frozen pytest -k test_sync
